name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/myapp:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/myapp:latest

        # 4️⃣ 更新 GitOps 仓库
      - name: Update Kubernetes repo
        run: |
          git clone https://${{ secrets.GIT_TOKEN }}@github.com/${{ secrets.DOCKER_USERNAME }}/myapp-k8s.git
          cd myapp-k8s

          # 修改 deployment.yaml 里的 image
          sed -i "s|image: .*|image: ${{ secrets.DOCKER_USERNAME }}/myapp:${{ github.sha }}|g" deployment.yaml

          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git commit -am "Update image to ${{ github.sha }}"
          git push
